pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir '.jenkins'
        }
    }

    triggers {
        pollSCM('*/5 * * * 1-5')
    }

    stages {
        stage ('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'python setup.py install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
